# Copyright (c) 2021 aasaam software development group
image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$QUAY_HUB_USER --password=$QUAY_HUB_PASS quay.io
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    # build
    - docker build -f Dockerfile -t aasaam/geo-server .
    # push
    - |
      docker push aasaam/geo-server
      docker image tag aasaam/geo-server quay.io/aasaam/geo-server
      docker push quay.io/aasaam/geo-server
      docker image tag aasaam/geo-server docker.pkg.github.com/aasaam/geo-server/geo-server
      docker push docker.pkg.github.com/aasaam/geo-server/geo-server
      docker image tag aasaam/geo-server $CI_REGISTRY/aasaam/geo-server:latest
      docker push $CI_REGISTRY/aasaam/geo-server:latest
    # remove image
    - docker rmi aasaam/geo-server
