version: '3'

services:
  geo-server:
    container_name: geo-server
    image: aasaam/geo-server
    volumes:
      - cache-storage:/cache
    network_mode: "host"
    environment:
      BIND_ADDRESS: 127.0.0.1:48080
      HTTP_PROXY: ''
      HTTPS_PROXY: ''
    restart: unless-stopped

volumes:
  cache-storage:
