version: '3'

services:
  geo-server:
    container_name: geo-server
    image: aasaam/geo-server
    volumes:
      - cache-storage:/cache
    network_mode: "host"
    environment:
      LISTEN_HOST: 127.0.0.1
      LISTEN_PORT: 48080
      HTTP_PROXY: ''
      # HTTP_PROXY: 'http://127.0.0.1:8080'
    restart: unless-stopped

volumes:
  cache-storage:
