# Copyright (c) 2021 aasaam software development group
version: '3'

services:
  geo-server:
    container_name: geo-server
    image: aasaam/geo-server
    volumes:
      - cache-storage:/cache
    network_mode: "host"
    environment:
      LISTEN_HOST: ${LISTEN_HOST:127.0.0.1}
      LISTEN_PORT: ${LISTEN_PORT:9560}
    restart: unless-stopped

volumes:
  cache-storage:
